### ISSUE TITLE
error on server with meteor shell active

### ISSUE THREAD

**Issue by garenor** [djhi/meteor-moment-languages#1]
I'm getting errors on the server if I have a second terminal window open with an active Meteor Shell. The error is `TypeError: Cannot call method 'defineLocale' of undefined`. As long as I have Meteor Shell open I can't restart the server (terrible while developing ;)

Some lines from the error tracelog:

```
at moment.defineLocale.months (packages/gildaspk:moment-languages/lib/locales.js:13:1)
at moment.defineLocale.months (packages/gildaspk:moment-languages/lib/locales.js:11:1)
```

I am using Dutch as language.

Hopefully you have some pointers how to remedy the error. Thanks.

**Comment by djhi** [comment]
Can't reproduce this prb. I have tried with several terminal and meteor shell. Are you sure you're using the last version of this package: `2.9.0` ?

**Comment by garenor** [comment]
Yes, `momentjs:moment@2.9.0` and `gildaspk:moment-languages@2.9.0`. 

I will try to create a repro of this, and will send you a github link if I have this working.

**Comment by dcsan** [comment]
im getting this too. i had no idea why suddenly my server is crashing, oh because another shell is open? bizarre

```
W20150510-10:12:47.268(-7)? (STDERR) 
W20150510-10:12:47.269(-7)? (STDERR) /Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150510-10:12:47.269(-7)? (STDERR)                        throw(ex);
W20150510-10:12:47.269(-7)? (STDERR)                              ^
W20150510-10:12:47.306(-7)? (STDERR) TypeError: Cannot call method 'defineLocale' of undefined
W20150510-10:12:47.306(-7)? (STDERR)     at moment.defineLocale.months (packages/flamparski:moment-locales/bower_components/moment/locale/en-au.js:18:1)
W20150510-10:12:47.306(-7)? (STDERR)     at moment.defineLocale.months (packages/flamparski:moment-locales/bower_components/moment/locale/en-au.js:10:1)
W20150510-10:12:47.306(-7)? (STDERR)     at packages/flamparski:moment-locales/bower_components/moment/locale/en-au.js:17:1
W20150510-10:12:47.306(-7)? (STDERR)     at /Users/dc/dev/shumi/chatu/app/.meteor/local/build/programs/server/packages/flamparski_moment-locales.js:2964:4
W20150510-10:12:47.306(-7)? (STDERR)     at /Users/dc/dev/shumi/chatu/app/.meteor/local/build/programs/server/packages/flamparski_moment-locales.js:3084:3
W20150510-10:12:47.306(-7)? (STDERR)     at /Users/dc/dev/shumi/chatu/app/.meteor/local/build/programs/server/boot.js:222:10
W20150510-10:12:47.307(-7)? (STDERR)     at Array.forEach (native)
W20150510-10:12:47.307(-7)? (STDERR)     at Function._.each._.forEach (/Users/dc/.meteor/packages/meteor-tool/.1.1.3.ylpo7g++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150510-10:12:47.307(-7)? (STDERR)     at /Users/dc/dev/shumi/chatu/app/.meteor/local/build/programs/server/boot.js:117:5
```

**Comment by garenor** [comment]
Strange thing is, I can't reproduce this in a clean project.

**Comment by robwatkin** [comment]
If it's any help I'm getting this too

```
W20150609-19:41:14.948(1)? (STDERR)
W20150609-19:41:14.948(1)? (STDERR) /Users/rob/.meteor/packages/meteor-tool/.1.1.3.s58u74++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150609-19:41:14.948(1)? (STDERR)                         throw(ex);
W20150609-19:41:14.948(1)? (STDERR)                               ^
W20150609-19:41:14.951(1)? (STDERR) TypeError: Cannot call method 'defineLocale' of undefined
W20150609-19:41:14.951(1)? (STDERR)     at app/lib/momentjs/en-gb.js:14:19
W20150609-19:41:14.951(1)? (STDERR)     at moment.defineLocale.months (app/lib/momentjs/en-gb.js:11:9)
W20150609-19:41:14.952(1)? (STDERR)     at app/lib/momentjs/en-gb.js:13:2
W20150609-19:41:14.952(1)? (STDERR)     at app/lib/momentjs/en-gb.js:67:3
W20150609-19:41:14.952(1)? (STDERR)     at /Users/rob/Documents/....../sapp/.meteor/local/build/programs/server/boot.js:222:10
W20150609-19:41:14.952(1)? (STDERR)     at Array.forEach (native)
W20150609-19:41:14.952(1)? (STDERR)     at Function._.each._.forEach (/Users/rob/.meteor/packages/meteor-tool/.1.1.3.s58u74++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150609-19:41:14.952(1)? (STDERR)     at /Users/rob/Documents/........./sapp/.meteor/local/build/programs/server/boot.js:117:5
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
```
